DROP DATABASE IF EXISTS PrescriptionsDB;
GO 

CREATE DATABASE PrescriptionsDB ;

USE PrescriptionsDB ;
GO

ALTER TABLE [dbo].[Prescriptions] 
ADD CONSTRAINT fk_Medical_Practice  FOREIGN KEY (PRACTICE_CODE) REFERENCES 
Medical_Practice (PRACTICE_CODE);
GO


ALTER TABLE [dbo].[Prescriptions] 
ADD CONSTRAINT fk_Drugs  FOREIGN KEY (BNF_CODE) REFERENCES Drugs (BNF_CODE);
GO


--Question 2
SELECT *
FROM dbo.Drugs
WHERE [BNF_DESCRIPTION] LIKE '%tablet%' or  [BNF_DESCRIPTION] LIKE '%capsule%' ;
GO


--Question 3
SELECT d.CHEMICAL_SUBSTANCE_BNF_DESCR, p.PRESCRIPTION_CODE, ROUND ((p.ITEMS * P.QUANTITY),0) AS Total_quantity
FROM [dbo].[Prescriptions] p
JOIN dbo.Drugs d
ON p.BNF_CODE=  d.BNF_CODE

--Question4

SELECT DISTINCT(CHEMICAL_SUBSTANCE_BNF_DESCR)
FROM dbo.Drugs
ORDER BY CHEMICAL_SUBSTANCE_BNF_DESCR
GO

--Question 5


SELECT d.BNF_CHAPTER_PLUS_CODE, COUNT(*) AS No_of_Prescription,
AVG(p.ACTUAL_COST) AS Avg_Cost_Prescription, MIN(p.ACTUAL_COST)  AS Min_Cost_Prescription,
MAX(p.ACTUAL_COST)  AS Max_Cost_Prescription
FROM [dbo].[Prescriptions] p
JOIN dbo.Drugs d
on p.BNF_CODE = d.BNF_CODE
GROUP BY d.BNF_CHAPTER_PLUS_CODE
ORDER BY d.BNF_CHAPTER_PLUS_CODE;
GO

--Question 6

SELECT PRACTICE_CODE, MAX(ACTUAL_COST) AS Maximum_cost
FROM dbo.Prescriptions
GROUP BY PRACTICE_CODE
HAVING MAX(ACTUAL_COST)>4000
ORDER BY MAX(ACTUAL_COST) DESC;
GO

--Question 7a 
SELECT m.PRACTICE_NAME, 
               COUNT(d.CHEMICAL_SUBSTANCE_BNF_DESCR) AS NO_OF_CHEMICAL_SUBSTANCE 
FROM dbo.Prescriptions p
JOIN dbo.Drugs d 
ON p.BNF_CODE = d.BNF_CODE
JOIN dbo.Medical_Practice m
ON p.PRACTICE_CODE= m.PRACTICE_CODE
GROUP BY m.PRACTICE_NAME
ORDER BY COUNT(d.CHEMICAL_SUBSTANCE_BNF_DESCR) DESC
GO

--Question 7b
SELECT  m.ADDRESS_1, m.POSTCODE, SUM(p.Actual_Cost) AS Total_Cost
FROM dbo.Medical_Practice m
INNER JOIN dbo.Prescriptions p
ON p.PRACTICE_CODE = p.PRACTICE_CODE
GROUP BY  m.ADDRESS_3,m.POSTCODE,m.ADDRESS_1
HAVING m.ADDRESS_3 IN( 'FARNWORTH' , 'HALLIWELL')

--QUESTION 7c
SELECT DISTINCT(ADDRESS_1)
FROM Medical_Practice
ORDER BY ADDRESS_1



--QUESTION 7D
--
SELECT TOP(10) d.BNF_Description, COUNT(*) AS Prescription_Count
FROM Prescriptions p
JOIN Drugs d
ON p.BNF_CODE = d.BNF_CODE
GROUP BY d.BNF_Description
ORDER BY Prescription_Count DESC

--QUESTION 7e 
-- Query retrieves drugs and presciption details
SELECT *
FROM Prescriptions p
JOIN Drugs d
ON p.BNF_CODE = d.BNF_CODE




SELECT PRESCRIPTION_CODE, MAX(QUANTITY*ITEMS*ACTUAL_COST) AS Total_Cost
FROM Prescriptions
GROUP BY PRESCRIPTION_CODE
ORDER BY MAX(QUANTITY*ITEMS*ACTUAL_COST) DESC;

SELECT COUNT(PRACTICE_CODE), POSTCODE
FROM Medical_Practice
WHERE POSTCODE IN( 'BL1%' , 'BL2%')
GROUP BY POSTCODE

SELECT COUNT(PRACTICE_CODE), POSTCODE
FROM Medical_Practice
WHERE POSTCODE IN( 'BL1%' , 'BL2%')
GROUP BY POSTCODE
GO

SELECT  m.ADDRESS_1, m.POSTCODE, SUM(p.Actual_Cost) AS Total_Cost
FROM dbo.Medical_Practice m
INNER JOIN dbo.Prescriptions p
ON p.PRACTICE_CODE = p.PRACTICE_CODE
GROUP BY m.[ADDRESS_3],  m.POSTCODE,m.ADDRESS_1
HAVING m.ADDRESS_3 IN( 'FARNWORTH' , 'HALLIWELL')

SELECT  m.ADDRESS_1, m.POSTCODE, SUMp.Actual_Cost
FROM dbo.Medical_Practice m
INNER JOIN dbo.Prescriptions p
ON p.PRACTICE_CODE = p.PRACTICE_CODE
WHERE m.ADDRESS_3 IN( 'FARNWORTH' , 'HALLIWELL')
GROUP BY m.[ADDRESS_3],  m.POSTCODE,m.ADDRESS_1

--Question 7a 
SELECT m.PRACTICE_NAME, 
               COUNT(d.CHEMICAL_SUBSTANCE_BNF_DESCR) AS NO_OF_CHEMICAL_SUBSTANCE 
FROM dbo.Prescriptions p
JOIN dbo.Drugs d 
ON p.BNF_CODE = d.BNF_CODE
JOIN dbo.Medical_Practice m
ON p.PRACTICE_CODE= m.PRACTICE_CODE
GROUP BY m.PRACTICE_NAME
ORDER BY COUNT(d.CHEMICAL_SUBSTANCE_BNF_DESCR) DESC
GO

--Question 7b
SELECT  DISTINCT(BNF_CHAPTER_PLUS_CODE) AS NO_OF_BNF, BNF_CHAPTER_PLUS_CODE
FROM Drugs
GROUP BY BNF_CHAPTER_PLUS_CODE

SELECT PRACTICE_NAME, CONCAT (ADDRESS_1, + ' ' + ADDRESS_2, + ' ' +ADDRESS_3, + ' '+ ADDRESS_4, + ' ' + POSTCODE )
FROM (SELECT POSTCODE FROM Medical_Practice WHERE POSTCODE LIKE 'BL7%')
WHERE ADDRESS_3 LIKE 'BROMLEY CROSS' 

SELECT PrescriptionsDB
SELECT PRACTICE_CODE, CONCAT(ADDRESS_1, + ' ' + ADDRESS_2, + ' ' +ADDRESS_3, + ' '+ ADDRESS_4, + ' ' + POSTCODE ) AS ADDRESS
FROM Medical_Practice


SELECT *
FROM DRUGS

SELECT * 
FROM Prescriptions

SELECT *
FROM Medical_Practice
GO

--This works
SELECT CHEMICAL_SUBSTANCE_BNF_DESCR
FROM Drugs
WHERE EXISTS (SELECT * FROM Prescriptions  
WHERE Prescriptions.BNF_CODE= Drugs.BNF_CODE AND  ACTUAL_COST >10)
GO

--IT WORKS 
SELECT m.PRACTICE_NAME, Max(p.Quantity) AS maximum_quantity
FROM Prescriptions p
join Medical_Practice m
on m.PRACTICE_CODE= p.PRACTICE_CODE
group by m.PRACTICE_NAME
having Max(p.Quantity) > 45000
order by Max(p.Quantity) desc